### ISSUE TITLE
Function and constructor name clash

### ISSUE THREAD

**Issue by Kakadu** [Lozov-Petr/noCanren#6]
When we have function `subordinate` and consstructor `Subordinate` they induce two functions with names `subordinate`. 
Maybe we should detect this and alert a warning.

@Lozov-Petr

**Comment by Kakadu** [comment]
Also, maybe we should warn when a function returns values of type `[some -> function]` because unification of functions in OCanren is not defined.

**Comment by Lozov-Petr** [comment]
Now we use constructors instead constructor-based functions.
